### ISSUE TITLE
The stream starts only when the track is full loaded

### ISSUE THREAD

**Issue by franz976** [kilokeith/soundcloud-soundmanager-player#15]
Hi
Thank you for such a great player! I got a problem: I'd like the track to be streamed on the event "scplayer.track.bindable", while now it seems it doesn't start until the event "scplayer.track.ready". 
Can you help me?

Thanks in adavance
Francesco

**Comment by kilokeith** [comment]
I haven't touched this in awhile so I'm not positive, but ***track.bindable*** is the earliest possible time that you can bind events to the object, while ***track.ready*** is the earliest you can call commands on the track. It shouldn't have to be fully buffered for that to happen. Maybe soundmanager2 changed something internally and that's why it's buffering. Just a guess.

**Comment by bdebon** [comment]
Same problem here... So sad ! 
The funny thing is when you click the play button right after you've clicked on a song from the list, it actually play directly the song without waiting. But if you only click on the song, you have the wait the song is totally buffered before you hear some sounds...
I know that it is an old project of yours and you don't have specially the time to take a look but if maybe you have an idea, I am listening to you !

Anyway, your work is fantastic ! Thank you very much !

**Comment by bdebon** [comment]
Ok, don't know if my trick can help you franz976 but theses lines play your music as soon as you click on the song.

<code>
scplayer.on("scplayer.track.bindable", function(e){
                scplayer.pause();
            });
</code>

Hope it helps !
